{
    'name': 'Aloette',
    'category': 'Generic Modules/Human Resources',
    'author': 'GeoiWorks',
    'version': '17.0.1.0.2',
    'sequence': 3,
    'license': 'LGPL-3',
    'summary': 'Skin care management system for aloette',
    'description': """Skin care management system for aloette.""",
    'depends': ['web', 'stock', 'sale_management', 'contacts'],
    'data': [
        'views/skin_consultation_views.xml',
        'views/product.xml',
        'views/hide_menus.xml',
        'reports/aloette_invoice_template.xml',
        'reports/alette_invoice.xml',
        'reports/cosmedix_invoice_template.xml',
        'reports/cosmedix_invoice.xml',
        'reports/sales_order_template.xml',
        'reports/sales_order.xml',
        'reports/purchase_order_template.xml',
        'reports/purchase_order.xml',
        'views/purchase_order.xml',
        'views/sales_order.xml',
        'views/invoice_inherit.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'aloette/static/src/components/skin_consultation/skin_consultation.xml',
            'aloette/static/src/components/skin_consultation/skin_consultation.js',
            'aloette/static/src/components/skin_consultation/skin_consultation.scss',
            # 'aloette/static/src/js/change_title.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'application': True,
}
